/** 
let data = '[{"rice":200,"alo":330,"potol":120,"location":"Kacabazer"},{"rice":39,"alo":300,"potol":120,"location":"Kacabazer"},{"rice":29,"alo":300,"potol":120,"location":"Kacabazer"},{"rice":239,"alo":300,"potol":10,"location":"Kacabazer"},{"rice":29,"alo":400,"potol":20,"location":"Kacabazer"}]';
 let data2 = '[{"rice":200,"alo":330,"potol":120,"location":"Kacabazer"},{"rice":39,"alo":300,"potol":120,"location":"Kacabazer"},{"rice":29,"alo":300,"potol":120,"location":"Kacabazer"},{"rice":239,"alo":300,"potol":10,"location":"Kacabazer"},{"rice":29,"alo":400,"potol":20,"location":"Kacabazer"}]';
 let data3 = '[{"rice":200,"alo":330,"potol":120,"location":"Kacabazer"},{"rice":39,"alo":300,"potol":120,"location":"Kacabazer"},{"rice":29,"alo":300,"potol":120,"location":"Kacabazer"},{"rice":239,"alo":300,"potol":10,"location":"Kacabazer"},{"rice":29,"alo":400,"potol":20,"location":"Kacabazer"}]';

//  const ob = [data, data2, data3];
// console.log(J);
*/
let phonbook = '[{"id":1,"Name":"Joy Sarker","skill":"MERN","Location":"Gulshan","fee":500,"Gender":"Male","age":30},{"id":2,"Name":"Bijoy Shill","skill":"MERN","Location":"Gulshan","fee":500,"Gender":"Male","age":34},{"id":3,"Name":"Abbus vaai","skill":"Wordpress","Location":"Mirpur","fee":300,"Gender":"Male","age":23},{"id":4,"Name":"Malak akanda","skill":"Wordpress","Location":"Mirpur","fee":350,"Gender":"Male","age":26},{"id":5,"Name":"Tohid vai","skill":"PHP","Location":"Banani","fee":600,"Gender":"Male","age":18},{"id":6,"Name":"Toffazol hossin","skill":"PHP","Location":"Banani","fee":200,"Gender":"Male","age":23},{"id":7,"Name":"Asok Sarker","skill":"Payton","Location":"Gazipur","fee":500,"Gender":"Male","age":22},{"id":8,"Name":"Nobi hossin","skill":"Payton","Location":"Gazipur","fee":800,"Gender":"Male","age":29},{"id":9,"Name":"Jagoron Roy","skill":"Golang","Location":"Mhammadpur","fee":400,"Gender":"Male","age":23},{"id":10,"Name":"Jannatul-fardous","skill":"Golang","Location":"Mhammadpur","fee":900,"Gender":"Female","age":23}]';

let phonebok2 = 'app.js:109 [{"id":1,"Name":"Joy Sarker","skill":"MERN","Location":"Gulshan","fee":500,"Gender":"Male","age":30},{"id":2,"Name":"Bijoy Shill","skill":"MERN","Location":"Gulshan","fee":500,"Gender":"Male","age":34},{"id":3,"Name":"Abbus vaai","skill":"Wordpress","Location":"Mirpur","fee":300,"Gender":"Male","age":23},{"id":4,"Name":"Malak akanda","skill":"Wordpress","Location":"Mirpur","fee":350,"Gender":"Male","age":26},{"id":5,"Name":"Tohid vai","skill":"PHP","Location":"Banani","fee":600,"Gender":"Male","age":18},{"id":6,"Name":"Toffazol hossin","skill":"PHP","Location":"Banani","fee":200,"Gender":"Male","age":23},{"id":7,"Name":"Asok Sarker","skill":"Payton","Location":"Gazipur","fee":500,"Gender":"Male","age":22},{"id":8,"Name":"Nobi hossin","skill":"Payton","Location":"Gazipur","fee":800,"Gender":"Male","age":29},{"id":9,"Name":"Jagoron Roy","skill":"Golang","Location":"Mhammadpur","fee":400,"Gender":"Male","age":23},{"id":10,"Name":"Jannatul-fardous","skill":"Golang","Location":"Mhammadpur","fee":900,"Gender":"Female","age":23}]';
let phonbok3  = 'app.js:109 [{"id":1,"Name":"Joy Sarker","skill":"MERN","Location":"Gulshan","fee":500,"Gender":"Male","age":30},{"id":2,"Name":"Bijoy Shill","skill":"MERN","Location":"Gulshan","fee":500,"Gender":"Male","age":34},{"id":3,"Name":"Abbus vaai","skill":"Wordpress","Location":"Mirpur","fee":300,"Gender":"Male","age":23},{"id":4,"Name":"Malak akanda","skill":"Wordpress","Location":"Mirpur","fee":350,"Gender":"Male","age":26},{"id":5,"Name":"Tohid vai","skill":"PHP","Location":"Banani","fee":600,"Gender":"Male","age":18},{"id":6,"Name":"Toffazol hossin","skill":"PHP","Location":"Banani","fee":200,"Gender":"Male","age":23},{"id":7,"Name":"Asok Sarker","skill":"Payton","Location":"Gazipur","fee":500,"Gender":"Male","age":22},{"id":8,"Name":"Nobi hossin","skill":"Payton","Location":"Gazipur","fee":800,"Gender":"Male","age":29},{"id":9,"Name":"Jagoron Roy","skill":"Golang","Location":"Mhammadpur","fee":400,"Gender":"Male","age":23},{"id":10,"Name":"Jannatul-fardous","skill":"Golang","Location":"Mhammadpur","fee":900,"Gender":"Female","age":23}]';

const all = [phonbook, phonebok2, phonbok3];

console.log(JSON.stringify(all[1]));